package com.api;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.*;
import java.sql.*;

public class Main {

    static final String url = "jdbc:mysql://localhost:3306/database1";
    static final String user = "root";
    static final String pw = "SuperSecure!";

    public static void main(String[] args) {

        //Add whatever testing you want here

        System.out.println("Let's have a test run!\n");

        System.out.println("First, let's make a superadmin who can make universities");

        createUser("super_admin", "super_admin", "super_admin@ucf.edu", "super_admin", -1);

        System.out.println("When the frontend with the right request, the backend verifies and passes the uid to the function");

        int superAdminID = validateUser("super_admin@ucf.edu", "super_admin");

        System.out.println("Super admin Id is " + superAdminID);

        System.out.println("Now, let's make two universities now that we have a super_admin");

        int uni = createUniversity(superAdminID,"UCF", 60000, "University of Central Florida");

        System.out.println("Made university with ID: " + uni);

        int uni2 = createUniversity(superAdminID,"UF", 40000, "University of Florida");

        System.out.println("Made university with ID: " + uni2);


        System.out.println("Create 5 students and one admin for UCF");

        for (int i = 0; i < 5; i++){

            if (createUser("student", String.valueOf(i), String.valueOf(i) + "@ucf.edu", String.valueOf(i), uni) > 0){
                System.out.println("Created student: " + i);
            }

        }

        int adminId = createUser("admin", "admin", "admin" + "@ucf.edu", "admin", uni);


        System.out.println("All our users have been created.\n");


        System.out.println("Now let's create three events of each type");


        //THE FOLLOWING WAS GENERATED BY AI FOR SAKE OF TIME

        double longitude = -73.935242; // Example longitude
        double latitude = 40.730610;   // Example latitude

        Event publicEvent = new Event(
                "Public Event",
                "This is a public event description.",
                LocalDate.of(2025, 5, 1),
                LocalTime.of(10, 0),
                LocalTime.of(12, 0)
        );

        int resultPublic = createEvent(publicEvent, adminId, uni, "public", longitude, latitude, 0);


        Event privateEvent = new Event(
                "Private Event",
                "This is a private event description.",
                LocalDate.of(2025, 5, 2),
                LocalTime.of(11, 0),
                LocalTime.of(13, 0)
        );

        int resultPrivate = createEvent(privateEvent, adminId, uni, "private", longitude, latitude, 0);
        Event rsoEvent = new Event(
                "RSO Event",
                "This is an RSO event description.",
                LocalDate.of(2025, 5, 3),
                LocalTime.of(14, 0),
                LocalTime.of(16, 0)
        );

        int rsoId = createRso("Databasers", "Databases", uni, "admin@ucf.edu", "@ucf.edu"); // Example rso_id for RSO event.
        int resultRso = createEvent(rsoEvent, adminId, uni, "rso", longitude, latitude, rsoId);

        System.out.println(resultPublic + " " + resultRso + " " + resultPrivate);

    }


    

    //Function for a superadmin to approve an event
    public static boolean approveEvent(int eventId, int userId){

        //If the user isn't a superadmin
        if (!isSuperAdmin(userId)){
            return false;
        }

        String sql = "UPDATE public_events SET approved = TRUE WHERE event_id = ?";

        try (Connection conn = DriverManager.getConnection(url, user, pw);
            PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            ps.setInt(1, eventId);
            int affectedRows = ps.executeUpdate();

            return affectedRows > 0;
        }
        catch (SQLException e) {
            e.printStackTrace();
            return false;
        }

    }


    //Function to add a new comment to our DB
    public static boolean addComment(int event_id, int user_id, String text, int rating, Timestamp date){

        String sql = "INSERT INTO comments (event_id, user_id, text, rating, timestamp) VALUES (?, ?, ?, ?, ?)";

        try (Connection conn = DriverManager.getConnection(url, user, pw);
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, event_id);
            stmt.setInt(2, user_id);
            stmt.setString(3, text);
            stmt.setInt(4, rating);
            stmt.setTimestamp(5, date);

            int rowsAffected = stmt.executeUpdate();
            return rowsAffected > 0;

        }
        catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    public static int createUniversity(int uid, String name, int students, String description){

        if (!isSuperAdmin(uid)){
            return -1;
        }

        String sql = "INSERT INTO university (name, students, description) VALUES (?, ?, ?)";

        try (Connection conn = DriverManager.getConnection(url, user, pw);
            PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            ps.setString(1, name);
            ps.setInt(2, students);
            ps.setString(3, description);

            int rowsAffected = ps.executeUpdate();
            if (rowsAffected == 0) {
                return -1;
            }

            try (ResultSet generatedKeys = ps.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    return generatedKeys.getInt(1);
                } else {
                    return -1;
                }
            }
        }
        catch (SQLException e) {
            e.printStackTrace();
            return -1;
        }
    }

    public static int createRso(String rso_name, String description, int universityID, String admin_email, String email_domain){

        String sql = "INSERT INTO rso (rso_name, description, universityID, admin_email, email_domain) VALUES (?, ?, ?, ?, ?)";
        try (Connection conn = DriverManager.getConnection(url, user, pw);
            PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, rso_name);
            stmt.setString(2, description);
            stmt.setInt(3, universityID);
            stmt.setString(4, admin_email);
            stmt.setString(5, email_domain);

            int rowsAffected = stmt.executeUpdate();
            if (rowsAffected == 0) {
                return -1;
            }

            try (ResultSet generatedKeys = stmt.getGeneratedKeys()){
                if (generatedKeys.next()){
                    return generatedKeys.getInt(1);
                }
                else{
                    return -1;
                }
            }
        }
        catch (SQLException e){
            e.printStackTrace();
            return -1;
        }
    }

    //Function to get student's university

    public static int getStudentUni(int uid) {
        String sql = "SELECT university_id FROM student WHERE uid = ?";
        try (Connection conn = DriverManager.getConnection(url, user, pw);
             PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setInt(1, uid);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt("university_id");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return -1; // Returning -1 indicates that no matching record was found or an error occurred.
    }

    //Function to get university of rso

    public static int getRsoUni(int rso_id) {
        String sql = "SELECT university_id FROM rso WHERE uid = ?";
        try (Connection conn = DriverManager.getConnection(url, user, pw);
             PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setInt(1, rso_id);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt("university_id");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return -1; // Returning -1 indicates that no matching record was found or an error occurred.
    }

    public static boolean joinRso(int rso_id, int uid){


        //Only student of certain university can join rsos for that university
        int rsoUni = getRsoUni(rso_id);
        int studentUni = getStudentUni(uid);

        if (studentUni == -1 || rsoUni != studentUni){
            return false;
        }



        String sql = "INSERT INTO user_rso (rso_id, user_id) VALUES (?, ?, ?)";

        try (Connection conn = DriverManager.getConnection(url, user, pw);
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, rso_id);
            stmt.setInt(2, uid);

            int rowsAffected = stmt.executeUpdate();
            return rowsAffected > 0;

        }
        catch (SQLException e) {
            e.printStackTrace();
            return false;
        }

    }



    //Returns a list of comments based on whatever event we're indexing
    public static List<Comment> getComments(int event_id){

        List<Comment> comments = new ArrayList<>();
        String sql = "SELECT * FROM comments WHERE event_id = ?";

        try (Connection conn = DriverManager.getConnection(url, user, pw);
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, event_id);

            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {

                    //Set all the variables (for easier readability)
                    int eid = rs.getInt("event_id");
                    int uid = rs.getInt("user_id");
                    String text = rs.getString("text");
                    int rating = rs.getInt("rating");
                    Timestamp t = rs.getTimestamp("timestamp");

                    Comment comment = new Comment(eid, uid, text, rating,t);

                    //Add the new comment
                    comments.add(comment);
                }
            }
        }
        catch (SQLException e){
            e.printStackTrace();
        }

        return comments;
    }

    //Code -1 = no permission
    //Code 0 = failed
    //Code 1 = success
    public static int createEvent(Event event, int ownerId, int university_id, String eventType, double longitude, double latitude, int rso_id){

        //If there aren't permissions to create an event
        if (!isAdmin(ownerId) && !isSuperAdmin(ownerId)){

            return -1;
        }

        int locationId = getLocationId(longitude, latitude);


        //If location doesn't exist, make it
        if (locationId == -1){
            locationId = insertLocation(longitude, latitude);
        }


        Connection conn = null;
        PreparedStatement ps = null;

        try {
            conn = DriverManager.getConnection(url, user, pw);
            conn.setAutoCommit(false);

            //Insert into events table and retrieve generated keys.
            String sqlInsertEvent = "INSERT INTO events (title, description, date, start, end, university_id, locID) VALUES (?, ?, ?, ?, ?, ?,?)";
            ps = conn.prepareStatement(sqlInsertEvent, Statement.RETURN_GENERATED_KEYS);
            ps.setString(1, event.getTitle());
            ps.setString(2, event.getDescription());
            ps.setDate(3, java.sql.Date.valueOf(event.getDate()));
            ps.setTime(4, java.sql.Time.valueOf(event.getStart()));
            ps.setTime(5, java.sql.Time.valueOf(event.getEnd()));
            ps.setInt(6, university_id);
            ps.setInt(7, locationId);
            int affectedRows = ps.executeUpdate();

            if (affectedRows == 0) {
                conn.rollback();
                return 0;
            }

            //Retrieve the auto-generated event_id.
            int eventId;
            try (ResultSet generatedKeys = ps.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    eventId = generatedKeys.getInt(1);
                    event.setEventId(eventId);
                } else {
                    conn.rollback();
                    return 0;
                }
            }

            if (eventType.equalsIgnoreCase("rso")){

                String sql = "SELECT is_active FROM rso WHERE rso_id = ?";

                try (PreparedStatement psType = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)){

                    psType.setInt(1, rso_id);

                    try (ResultSet rs = psType.executeQuery()){
                        if (rs.next()){
                            boolean isActive = rs.getBoolean("is_active");
                            if (!isActive){
                                System.out.println("RSO is not active, lacks necessary members");
                                conn.rollback();
                                return 0;
                            }
                        }
                        else{
                            System.out.println("Rso could not be found!");
                            conn.rollback();
                            return 0;
                        }
                    }



                }

                String insert = "INSERT INTO rso_events(event_id, rso_id) VALUES (?, ?)";

                try(PreparedStatement ps2 = conn.prepareStatement(insert)){
                    ps2.setInt(1, eventId);
                    ps2.setInt(2, rso_id);
                    ps2.executeUpdate();
                }

            }

            //For private events, we don't need super admin approval
            else if (eventType.equalsIgnoreCase("private")){
                String sqlInsertType = "INSERT INTO private_events (event_id, owner_id) VALUES (?, ?)";
                try (PreparedStatement psType = conn.prepareStatement(sqlInsertType)) {
                    psType.setInt(1, eventId);
                    psType.setInt(2, ownerId);
                    psType.executeUpdate();
                }
            }

            //For public events, we set the approved to true if it's a super admin, otherwise false
            else if (eventType.equalsIgnoreCase("public")){
                boolean approved = isSuperAdmin(ownerId);
                String sqlInsertType = "INSERT INTO public_events (event_id, owner_id, approved) VALUES (?, ?, ?)";

                try (PreparedStatement psType = conn.prepareStatement(sqlInsertType)) {
                    psType.setInt(1, eventId);
                    psType.setInt(2, ownerId);
                    psType.setBoolean(3, approved);
                    psType.executeUpdate();
                }
            }
            conn.commit();
            return 1;
        }
        catch (SQLException e){
            e.printStackTrace();
            if (conn != null) {
                try {
                    conn.rollback();
                } catch (SQLException rollbackEx){
                    rollbackEx.printStackTrace();
                }
            }
            return 0;
        }
        finally {
            try {
                if (ps != null) {
                    ps.close();
                }
                if (conn != null) {
                    conn.setAutoCommit(true);
                    conn.close();
                }
            }
            catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }


    //Deletes an event based on the event's ID
    public static boolean deleteEvent(int eventId){

        String sql = "DELETE FROM events WHERE event_id = ?";

        try(Connection conn = DriverManager.getConnection(url, user, pw);
            PreparedStatement state = conn.prepareStatement(sql)){

            state.setInt(1, eventId);

            int rowsDeleted = state.executeUpdate();
            return rowsDeleted > 0;

        }
        catch (SQLException e){
            e.printStackTrace();
            return false;
        }
    }



    //Function to get all the events tied to a user
    public static List<Event> getEvents(int userId){
        String sql;
        List<Event> events = new ArrayList<>();

        if (isSuperAdmin(userId)){
            // For superadmins, return all events (without a specific event type)
            sql = "SELECT *, '' AS eventType FROM events";
        }
        else{
            sql = "SELECT e.*, 'public' AS eventType " +
                    "FROM events e " +
                    "JOIN public_events pe ON e.event_id = pe.event_id " +
                    "WHERE (pe.approved = TRUE OR pe.owner_id = ?) " +
                    "UNION " +

                    "SELECT e.*, 'private' AS eventType " +
                    "FROM events e " +
                    "JOIN student s ON e.university_id = s.university_id " +
                    "WHERE s.uid = ? " +
                    "UNION " +

                    "SELECT e.*, 'private' AS eventType " +
                    "FROM events e " +
                    "JOIN admin a ON e.university_id = a.university_id " +
                    "WHERE a.uid = ? " +
                    "UNION " +

                    "SELECT e.*, 'rso_events' AS eventType " +
                    "FROM events e " +
                    "JOIN rso_events re ON e.event_id = re.event_id " +
                    "JOIN user_rso ur ON re.rso_id = ur.rso_id " +
                    "WHERE ur.user_id = ?;";
        }

        try (Connection conn = DriverManager.getConnection(url, user, pw);
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            if (!isSuperAdmin(userId)){
                //Set parameters for the UNION query; one for public/private and one for RSO events
                stmt.setInt(1, userId); //public events
                stmt.setInt(2, userId); //private events
                stmt.setInt(3, userId); //private if admin
                stmt.setInt(4, userId); //rso events
            }

            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    Event event = new Event();
                    event.setEventId(rs.getInt("event_id"));
                    event.setTitle(rs.getString("title"));
                    event.setDescription(rs.getString("description"));
                    event.setDate(rs.getDate("date").toLocalDate());
                    event.setStart(rs.getTime("start").toLocalTime());
                    event.setEnd(rs.getTime("end").toLocalTime());
                    event.setAddressId(rs.getInt("address_id"));
                    event.setEventType(rs.getString("eventType")); // Set the event type field
                    events.add(event);
                }
            }
        }
        catch (SQLException e) {
            e.printStackTrace();
        }

        return events;
    }


    //Class event to return
    public static class Event {
        private int eventId;
        private String title;
        private String eventType;
        private String description;
        private LocalDate date;
        private LocalTime start;
        private LocalTime end;
        private int locID;

        public Event() {}

        public Event(String title, String description, LocalDate date, LocalTime start, LocalTime end) {
            this.title = title;
            this.description = description;
            this.date = date;
            this.start = start;
            this.end = end;
        }

        public LocalDate getDate(){
            return date;
        }
        public void setDate(LocalDate date){
            this.date = date;
        }

        public LocalTime getStart(){
            return start;
        }
        public void setStart(LocalTime start){
            this.start = start;
        }
        public LocalTime getEnd(){
            return end;
        }
        public void setEnd(LocalTime end){
            this.end = end;
        }

        public int getEventId() {
            return eventId;
        }

        public void setEventId(int eventId) {
            this.eventId = eventId;
        }

        public void setEventType(String eventType){
            this.eventType = eventType;
        }

        public String getEventType(){
            return eventType;
        }

        public String getTitle() {
            return title;
        }

        public void setTitle(String title) {
            this.title = title;
        }

        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }



        public int getAddressId() {
            return locID;
        }

        public void setAddressId(int addressId) {
            this.locID = addressId;
        }

        @Override
        public String toString() {
            return "Event{" +
                    "eventId=" + eventId +
                    ", title='" + title + '\'' +
                    ", description='" + description + '\'' +
                    ", date=" +  date +
                    ", start=" +  start +
                    ", end=" +  end+
                    ", locID=" + locID +
                    '}';
        }
    }

    public static class Comment{

        private int event_id;
        private int user_id;
        private String text;
        private int rating;
        private Timestamp timestamp;


        public Comment(int event_id, int user_id, String text, int rating, Timestamp timestamp){
            this.event_id = event_id;
            this.user_id = user_id;
            this.text = text;
            this.rating = rating;
            this.timestamp = timestamp;
        }

        @Override
        public String toString(){

            return "Comment {"+ " event_id " + event_id + " user_id " + user_id + "\n text" + text + "\n rating" + rating + "\n timestamp" + timestamp;
        }

        public int getEventId(){
            return event_id;
        }

        public int getUserId(){
            return user_id;
        }

        public String getText(){
            return text;
        }

        public int getRating(){
            return rating;
        }
        public Timestamp getTimestamp(){
            return timestamp;
        }
    }


    //Check to see if the user already exists in our db based on user ID
    public static boolean existsUser(String email){

        String query = "SELECT COUNT(*) FROM users WHERE email = ?";

        try (Connection conn = DriverManager.getConnection(url, user, pw);
            PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setString(1, email);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    int count = rs.getInt(1);
                    return count > 0;
                }
            }
        }
        catch (SQLException e) {
            e.printStackTrace();
            return false;
        }

        return false;
    }


    //To validate a user when they attempt to sign in, communicates with frontend, and also gets the userID
    public static int validateUser(String email, String password) {
        String sql = "SELECT uid FROM users WHERE email = ? AND password = ?";
        try (Connection conn = DriverManager.getConnection(url, user, pw);
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, email);
            stmt.setString(2, password);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt("uid");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return -1;
    }



    //Checks to see if the location already exists
    public static int getLocationId(double longitude, double latitude) {
        String sql = "SELECT locID FROM locations WHERE longitude = ? AND latitude = ?";

        try (Connection conn = DriverManager.getConnection(url, user, pw);
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setDouble(1, longitude);
            stmt.setDouble(2, latitude);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt("locID");
                }
            }
        }
        catch (SQLException e) {
            e.printStackTrace();
        }
        return -1;
    }

    public static int insertLocation(double longitude, double latitude){

        String sql = "INSERT INTO locations (longitude, latitude) VALUES (?, ?)";

        try (Connection conn = DriverManager.getConnection(url, user, pw);
             PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setDouble(1, longitude);
            stmt.setDouble(2, latitude);

            int rowsAffected = stmt.executeUpdate();
            if (rowsAffected == 0) {
                return -1;
            }

            try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    return generatedKeys.getInt(1);
                } else {
                    return -1;
                }
            }
        }
        catch (SQLException e) {
            e.printStackTrace();
            return -1;
        }
    }



    //Check admin before executing something that needs admin perms
    public static boolean isAdmin(int uid){

        String query = "SELECT COUNT(*) FROM admin WHERE uid = ?";

        try (Connection conn = DriverManager.getConnection(url, user, pw);
            PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setInt(1, uid);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    int count = rs.getInt(1);
                    return count > 0;
                }
            }
        }
        catch (SQLException e) {
            e.printStackTrace();
            return false;
        }

        return false;
    }


    //Check superadmin before executing something that needs superadmin perms
    public static boolean isSuperAdmin(int uid){

        //If the uid shows up in the superadmin table, then it is a superadmin
        String query = "SELECT COUNT(*) FROM super_admin WHERE uid = ?";

        try (Connection conn = DriverManager.getConnection(url, user, pw);
            PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setInt(1, uid);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    int count = rs.getInt(1);
                    return count > 0;
                }
            }
        }
        catch (SQLException e) {
            e.printStackTrace();
            return false;
        }

        return false;
    }

    //Can do the same for superadmin, since we only have two types, no need to make anything fancier




    //To create a new user
    public static int createUser(String userType, String name, String email, String password, int universityId) {

        if (existsUser(email)){
            return -1;
        }
        try (Connection conn = DriverManager.getConnection(url, user, pw)) {

            conn.setAutoCommit(false);
            int uid;
            //Insert into users table
            String sql = "INSERT INTO users (name, email, password) VALUES (?, ?, ?)";
            try (PreparedStatement userStmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
                userStmt.setString(1, name);
                userStmt.setString(2, email);
                userStmt.setString(3, password);
                int affectedRows = userStmt.executeUpdate();

                if (affectedRows == 0) {
                    throw new SQLException("Error during user creation");
                }


                try (ResultSet generatedKeys = userStmt.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        uid = generatedKeys.getInt(1);
                    } else {
                        throw new SQLException("Failed to obtain a userID for the user");
                    }
                }
            }

            if (userType.equalsIgnoreCase("student")){

                //Check, each student must belong to a university
                if (universityId < 0){
                    return -1;
                }

                String insertStudent = "INSERT INTO student (uid, university_id) VALUES (?, ?)";

                try (PreparedStatement ps = conn.prepareStatement(insertStudent)) {
                    ps.setInt(1, uid);
                    ps.setInt(2, universityId);
                    ps.executeUpdate();
                }
            }


            //If user is admin
            if (userType.equalsIgnoreCase("admin")) {

                if (universityId < 0){
                    return -1;
                }
                String insertAdmin = "INSERT INTO admin  (uid, university_id) VALUES (?, ?)";
                try (PreparedStatement ps = conn.prepareStatement(insertAdmin)) {
                    ps.setInt(1, uid);
                    ps.setInt(2, universityId);
                    ps.executeUpdate();
                }
            }

            //If user is super_admin
            if (userType.equalsIgnoreCase("super_admin")) {
                String insertAdmin = "INSERT INTO super_admin (uid) VALUES (?)";
                try (PreparedStatement ps = conn.prepareStatement(insertAdmin)) {
                    ps.setInt(1, uid);
                    ps.executeUpdate();
                }
            }

            //Commit if both the inserts worked
            conn.commit();
            System.out.println("User created successfully");
            return uid;

        }
        catch (SQLException e) {
            e.printStackTrace();
            return -1;
        }
    }
}
